name: No API Breaking Changes

on:
  pull_request:
    branches: [main]
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - '.github/workflows/no-breaking-changes.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  breaking-changes:
    uses: request-dl/.github/.github/workflows/no-breaking-changes.yml@main
    with:
      swift-version: "6.1"
    secrets: inherit
